import type { IrSchema } from "@varavel/vdl-plugin-sdk";
import { hash as createHash } from "@varavel/vdl-plugin-sdk/utils/crypto";
import {
  firstParagraph as mdFirstParagraph,
  title as mdTitle,
} from "@varavel/vdl-plugin-sdk/utils/markdown";
import { isEmptyObject } from "@varavel/vdl-plugin-sdk/utils/predicates";
import { firstNChars, slugify } from "@varavel/vdl-plugin-sdk/utils/strings";
import { browser, dev } from "$app/environment";

/**
 * Browser global values injected by the generated VDL explorer bundle.
 *
 * @remarks
 * In production builds, the plugin injects `window.__vdl_ir` so the explorer can
 * load the schema without performing network requests.
 */
declare global {
  interface Window {
    /**
     * IR schema generated from source definitions.
     *
     * @remarks
     * This value is injected at build time by the VDL plugin runtime.
     */
    __vdl_ir?: IrSchema;
  }
}

/**
 * An empty IR schema used as a fallback when no IR is available.
 */
const EMPTY_IR: IrSchema = {
  entryPoint: "",
  types: [],
  enums: [],
  constants: [],
  docs: [],
};

/**
 * IR schema enriched with stable identifiers and derived documentation metadata.
 *
 * Each type, enum, constant, and doc receives an `id` and `urlPath` fields. Docs also
 * include a parsed `title` and `firstParagraph` for easier rendering and lookup.
 */
export type RichIrSchema = {
  entryPoint: string;
  types: (IrSchema["types"][number] & {
    id: string;
    urlPath: string;
  })[];
  enums: (IrSchema["enums"][number] & {
    id: string;
    urlPath: string;
  })[];
  constants: (IrSchema["constants"][number] & {
    id: string;
    urlPath: string;
  })[];
  docs: (IrSchema["docs"][number] & {
    id: string;
    urlPath: string;
    title: string;
    firstParagraph: string;
  })[];
};

/**
 * Build a deterministic, URL-friendly identifier for IR entities.
 *
 * The identifier combines a slugified label with the first 8 alphanumeric
 * characters of a content hash, producing stable IDs while reducing collision
 * risk across similarly named entities.
 *
 * @param name Human-readable entity label (for example, a type or enum name).
 * @param obj Entity payload used to derive the hash segment.
 * @returns Identifier in the form `<slug>-<hash8>`.
 */
function createId(name: string, obj: unknown): string {
  const slug = slugify(name);
  let hash = createHash(obj);
  hash = hash.replace(/[^a-zA-Z0-9]/g, "");
  hash = firstNChars(hash, 8, false);
  hash = hash.toLowerCase();
  return `${slug}-${hash}`;
}

/**
 * Enrich an IR schema with stable identifiers and derived doc metadata.
 *
 * IDs are generated by slugifying an item label (`name` or doc `title`) combined
 * with a hash of the item content, keeping them deterministic and collision-resistant.
 *
 * @param ir Base IR schema to enrich.
 * @returns Enriched IR schema with identifiers and doc presentation fields.
 */
function enrichIrSchema(ir: IrSchema): RichIrSchema {
  const types: RichIrSchema["types"] = ir.types.map((type) => {
    const id = createId(type.name, type);
    const urlPath = `#/types/${id}`;
    return { ...type, id, urlPath };
  });

  const enums: RichIrSchema["enums"] = ir.enums.map((en) => {
    const id = createId(en.name, en);
    const urlPath = `#/enums/${id}`;
    return { ...en, id, urlPath };
  });

  const constants: RichIrSchema["constants"] = ir.constants.map((constant) => {
    const id = createId(constant.name, constant);
    const urlPath = `#/constants/${id}`;
    return { ...constant, id, urlPath };
  });

  const docs: RichIrSchema["docs"] = ir.docs.map((doc) => {
    const title = mdTitle(doc.content);
    const firstParagraph = mdFirstParagraph(doc.content) ?? "";
    const id = createId(title, doc);
    const urlPath = `#/docs/${id}`;
    return { ...doc, id, urlPath, title, firstParagraph };
  });

  return {
    entryPoint: ir.entryPoint,
    types,
    enums,
    constants,
    docs,
  };
}

/**
 * Load a development IR schema mock from `ir.local.json`.
 *
 * @remarks
 * This function relies on Vite's `import.meta.glob` with an explicit root-relative
 * path to include the local mock file only when it exists.
 *
 * In development mode, place an `ir.local.json` file at the workspace root to
 * iterate on the explorer UI without running the plugin generation flow.
 *
 * @returns The mock IR schema when available; otherwise {@link EMPTY_IR}.
 */
function findMockIr(): IrSchema {
  type IrMockModule =
    | {
        default?: IrSchema;
      }
    | undefined;

  // Load the local IR mock file using Vite's import.meta.glob.
  const files = import.meta.glob("../../../../ir.local.json", { eager: true });

  const mockModule = files["../../../../ir.local.json"] as IrMockModule;
  if (!mockModule?.default) return EMPTY_IR;

  console.log("[DEV] Default IR loaded from ir.local.json");
  return mockModule.default;
}

/**
 * Check whether a non-empty IR payload is available on the browser global scope.
 *
 * @remarks
 * This acts as a guard before reading the runtime-injected payload and prevents
 * server-side access to `window`.
 *
 * @returns `true` when `window.__vdl_ir` exists and is not an empty object.
 */
function hasProductionIr(): boolean {
  return browser && !!window.__vdl_ir && !isEmptyObject(window.__vdl_ir);
}

/**
 * Load the runtime IR schema injected in browser production builds.
 *
 * @remarks
 * Server-side rendering and missing/empty injected payloads both fall back to
 * {@link EMPTY_IR} to guarantee a predictable shape for downstream consumers.
 *
 * @returns The injected runtime IR schema when available; otherwise {@link EMPTY_IR}.
 */
function findProductionIr(): IrSchema {
  if (!hasProductionIr()) return EMPTY_IR;
  return window.__vdl_ir as IrSchema;
}

/**
 * Load and normalize the IR schema for explorer store consumers.
 *
 * @remarks
 * - Runtime-injected schema (`window.__vdl_ir`) takes precedence when present.
 * - If no runtime payload is available and `dev` is enabled, `ir.local.json` is used.
 * - Otherwise, the loader falls back to {@link EMPTY_IR}.
 * - The resulting schema is always enriched through {@link enrichIrSchema}.
 *
 * @returns A rich IR schema containing stable `id` fields and parsed doc metadata.
 */
export function loadIrSchema(): RichIrSchema {
  if (hasProductionIr()) {
    return enrichIrSchema(findProductionIr());
  }

  if (dev) {
    return enrichIrSchema(findMockIr());
  }

  return enrichIrSchema(EMPTY_IR);
}
