import type { IrSchema } from "@varavel/vdl-plugin-sdk";
import { generateVdl } from "@varavel/vdl-plugin-sdk/utils/codegen";
import {
  firstParagraph as mdFirstParagraph,
  title as mdTitle,
} from "@varavel/vdl-plugin-sdk/utils/markdown";
import DOMPurify from "dompurify";
import { marked } from "marked";
import { highlighter } from "$lib/shiki";
import { createIrNodeLinkDictionary, createIrNodeRoute } from "./links";
import { createIrNodeLinkTransformer } from "./shiki-links-transformer";
import type { RichIrSchema } from "./types";

function markdownToHtmlDoc(markdown: string | undefined): string | undefined {
  if (markdown === undefined) {
    return undefined;
  }

  const parsed = marked.parse(markdown) as string;
  return DOMPurify.sanitize(parsed);
}

/**
 * Enrich an IR schema with stable identifiers and derived doc metadata.
 *
 * IDs are generated by slugifying an item label (`name` or doc `title`) combined
 * with a hash of the item content, keeping them deterministic and collision-resistant.
 *
 * @param ir Base IR schema to enrich.
 * @returns Enriched IR schema with identifiers and doc presentation fields.
 */
export async function enrichIrSchema(ir: IrSchema): Promise<RichIrSchema> {
  const linkDictionary = createIrNodeLinkDictionary(ir);
  const linkTransformer = createIrNodeLinkTransformer(linkDictionary);
  const shikiTransformers = [linkTransformer];

  const types: RichIrSchema["types"] = await Promise.all(
    ir.types.map(async (type) => {
      const { id, urlPath } = createIrNodeRoute("types", type.name, type);

      const raw = generateVdl(type, { docstrings: "strip-top-level" });
      const htmlLight = await highlighter.highlight(
        raw,
        "vdl",
        "light",
        shikiTransformers,
      );
      const htmlDark = await highlighter.highlight(
        raw,
        "vdl",
        "dark",
        shikiTransformers,
      );
      const sourceCode = { raw, htmlLight, htmlDark };
      const htmlDoc = markdownToHtmlDoc(type.doc);

      const sourceIr = { ...type };
      return { ...type, id, urlPath, htmlDoc, sourceCode, sourceIr };
    }),
  );

  const enums: RichIrSchema["enums"] = await Promise.all(
    ir.enums.map(async (en) => {
      const { id, urlPath } = createIrNodeRoute("enums", en.name, en);

      const raw = generateVdl(en, { docstrings: "strip-top-level" });
      const htmlLight = await highlighter.highlight(
        raw,
        "vdl",
        "light",
        shikiTransformers,
      );
      const htmlDark = await highlighter.highlight(
        raw,
        "vdl",
        "dark",
        shikiTransformers,
      );
      const sourceCode = { raw, htmlLight, htmlDark };
      const htmlDoc = markdownToHtmlDoc(en.doc);

      const sourceIr = { ...en };
      return { ...en, id, urlPath, htmlDoc, sourceCode, sourceIr };
    }),
  );

  const constants: RichIrSchema["constants"] = await Promise.all(
    ir.constants.map(async (constant) => {
      const { id, urlPath } = createIrNodeRoute(
        "constants",
        constant.name,
        constant,
      );

      const raw = generateVdl(constant, { docstrings: "strip-top-level" });
      const htmlLight = await highlighter.highlight(
        raw,
        "vdl",
        "light",
        shikiTransformers,
      );
      const htmlDark = await highlighter.highlight(
        raw,
        "vdl",
        "dark",
        shikiTransformers,
      );
      const sourceCode = { raw, htmlLight, htmlDark };
      const htmlDoc = markdownToHtmlDoc(constant.doc);

      const sourceIr = { ...constant };
      return { ...constant, id, urlPath, htmlDoc, sourceCode, sourceIr };
    }),
  );

  const docs: RichIrSchema["docs"] = ir.docs.map((doc) => {
    const title = mdTitle(doc.content);
    const firstParagraph = mdFirstParagraph(doc.content) ?? "";
    const { id, urlPath } = createIrNodeRoute("docs", title, doc);

    const raw = doc.content;
    const htmlLight = markdownToHtmlDoc(raw) ?? "";
    const htmlDark = htmlLight;
    const sourceCode = { raw, htmlLight, htmlDark };

    const sourceIr = { ...doc };
    return {
      ...doc,
      id,
      urlPath,
      title,
      firstParagraph,
      sourceCode,
      sourceIr,
    };
  });

  return {
    entryPoint: ir.entryPoint,
    types,
    enums,
    constants,
    docs,
  };
}
